name: contract
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: pip install cairo-lang
      - run: pip install starknet-devnet==0.1.22
      - run: npm install
      - run: npm run test
